Repository Team-Puzzling/Puzzling_iOS, pull requests merged in 2023-07, with the labels that each got.

#6 [Setting] #5 - UIColor Extension 에 Hex 를 사용하여 UIColor Assets 을 구축했습니다.
  Puzzling/Puzzling.xcodeproj/project.pbxproj
  Puzzling/Puzzling/Presentation/Home/IndivisualDashboard/IndivisualDashboardViewController.swift
  Puzzling/Puzzling/Presentation/Home/Main/View/DefaultUIViewFile.swift
  Puzzling/Puzzling/Presentation/Home/Main/ViewController/HomeViewController.swift
  Puzzling/Puzzling/Presentation/Home/TeamDashboard/TeamDashboardViewController.swift
  Puzzling/Puzzling/Util/NameSpace/Color.swift
Labels: 🦊 규보, ⚙️ Setting

#15 [Feature] #7 - 팀원 현황 View UI를 구현했습니다.
  Puzzling/Puzzling.xcodeproj/project.pbxproj
  Puzzling/Puzzling/Application/SceneDelegate.swift
  Puzzling/Puzzling/Presentation/TeamMember/DataModel/TeamMemberDataModel.swift
  Puzzling/Puzzling/Presentation/TeamMember/View/TeamMemberCustomHeaderView.swift
  Puzzling/Puzzling/Presentation/TeamMember/View/TeamMemberTableViewCell.swift
  Puzzling/Puzzling/Presentation/TeamMember/View/TeamMemberView.swift
  Puzzling/Puzzling/Presentation/TeamMember/ViewController/TeamMemberViewController.swift
  Puzzling/Puzzling/Util/NameSpace/Image.swift
Labels: 🌱 Feat, 😼 민주

#19 [Feature] #16 - 내 프로젝트 뷰 UI를 구현했습니다.
  Puzzling/Puzzling.xcodeproj/project.pbxproj
  Puzzling/Puzzling/Application/SceneDelegate.swift
  Puzzling/Puzzling/Data/DTO/MyProjectDataModel.swift
  Puzzling/Puzzling/Data/DTO/TeamMemberDataModel.swift
  Puzzling/Puzzling/Presentation/MyProject/View/MyProjectTableHeaderView.swift
  Puzzling/Puzzling/Presentation/MyProject/View/MyProjectTableViewCell.swift
  Puzzling/Puzzling/Presentation/MyProject/ViewController/MyProjectViewController.swift
  Puzzling/Puzzling/Presentation/TeamMember/View/TeamMemberCustomHeaderView.swift
  Puzzling/Puzzling/Presentation/TeamMember/View/TeamMemberTableViewCell.swift
  Puzzling/Puzzling/Presentation/TeamMember/View/TeamMemberView.swift
  Puzzling/Puzzling/Resource/AssetCatalog/Image.xcassets/icon/bell1.imageset/Contents.json
  Puzzling/Puzzling/Resource/AssetCatalog/Image.xcassets/icon/bell1.imageset/bell1.svg
  Puzzling/Puzzling/Resource/AssetCatalog/Image.xcassets/icon/notification.imageset/Contents.json
  Puzzling/Puzzling/Resource/AssetCatalog/Image.xcassets/icon/notification.imageset/notification.svg
  Puzzling/Puzzling/Util/Extension/String+.swift
  Puzzling/Puzzling/Util/NameSpace/Image.swift
Labels: 🌱 Feat, 😼 민주

#17 [Design] #11 - 프로젝트 등록 뷰 UI를 구현했습니다.
  Puzzling/Puzzling.xcodeproj/project.pbxproj
  Puzzling/Puzzling/Application/SceneDelegate.swift
  Puzzling/Puzzling/Data/Model/ProjectCycleModel.swift
  Puzzling/Puzzling/Presentation/CreateProject/Cell/ProjectCycleCollectionViewCell.swift
  Puzzling/Puzzling/Presentation/CreateProject/View/CreateProjectView.swift
  Puzzling/Puzzling/Presentation/CreateProject/View/InputContentView.swift
  Puzzling/Puzzling/Presentation/CreateProject/View/StartDayView.swift
  Puzzling/Puzzling/Presentation/CreateProject/ViewController/CreateProjectViewController.swift
  Puzzling/Puzzling/Resource/AssetCatalog/Image.xcassets/icon/textFieldxMark.imageset/Contents.json
  Puzzling/Puzzling/Resource/AssetCatalog/Image.xcassets/icon/textFieldxMark.imageset/Group 986628.svg
  Puzzling/Puzzling/Util/CustomClass/CheckButton.swift
Labels: 🦋 Design, 🐸 정

#25 [Feature] #18 - 프로젝트 등록 뷰 기능 구현
  Puzzling/Puzzling.xcodeproj/project.pbxproj
  Puzzling/Puzzling/Data/Model/textFieldNotificationModel.swift
  Puzzling/Puzzling/Presentation/CreateProject/Cell/ProjectCycleCollectionViewCell.swift
  Puzzling/Puzzling/Presentation/CreateProject/View/CreateProjectView.swift
  Puzzling/Puzzling/Presentation/CreateProject/View/InputContentView.swift
  Puzzling/Puzzling/Presentation/CreateProject/View/StartDayView.swift
  Puzzling/Puzzling/Presentation/CreateProject/ViewController/CreateProjectViewController.swift
  Puzzling/Puzzling/Presentation/CreateProject/ViewController/ProjectStartTimeViewController.swift
  Puzzling/Puzzling/Util/Extension/String+.swift
  Puzzling/Puzzling/Util/Extension/UIResponder+.swift
  Puzzling/Puzzling/Util/NameSpace/Image.swift
Labels: 🌱 Feat, 🐸 정

#31 [Setting] #30 - 서버 URL 초기세팅
  Puzzling/Puzzling/Network/Foundation/URLConst.swift
Labels: 🐸 정, ⚙️ Setting

#32 [Feature] #27 - 초대코드 입력 뷰 및 프로필 입력 뷰 구현
  Puzzling/Puzzling.xcodeproj/project.pbxproj
  Puzzling/Puzzling/Application/SceneDelegate.swift
  Puzzling/Puzzling/Presentation/CreateProject/View/InputContentView.swift
  Puzzling/Puzzling/Presentation/CreateProject/ViewController/CreateProjectViewController.swift
  Puzzling/Puzzling/Presentation/InvitationCode/ViewController/CreateProfileViewController.swift
  Puzzling/Puzzling/Presentation/InvitationCode/ViewController/InvitationCodeTestViewController.swift
  Puzzling/Puzzling/Presentation/InvitationCode/ViewController/InvitationCodeViewController.swift
  Puzzling/Puzzling/Resource/AssetCatalog/Image.xcassets/logo/Contents.json
  Puzzling/Puzzling/Resource/AssetCatalog/Image.xcassets/logo/invitationCodeLogo.imageset/Contents.json
  Puzzling/Puzzling/Resource/AssetCatalog/Image.xcassets/logo/invitationCodeLogo.imageset/Group 10.svg
  Puzzling/Puzzling/Util/NameSpace/Image.swift
Labels: 🌱 Feat, 🐸 정

#36 [Fix] #35 - 서버통신 초기세팅 URL 수정
  Puzzling/Puzzling/Network/Foundation/URLConst.swift
Labels: 🎈 Fix, 🐸 정, ⚙️ Setting

#34 [Feature] #24 - 회고작성 기능 구현 했습니다.
  Puzzling/Puzzling.xcodeproj/project.pbxproj
  Puzzling/Puzzling/Presentation/CreateProject/View/CustomAlertView.swift
  Puzzling/Puzzling/Presentation/CreateRetrospect/View/AARView.swift
  Puzzling/Puzzling/Presentation/CreateRetrospect/View/CustomAlert.swift
  Puzzling/Puzzling/Presentation/CreateRetrospect/View/FiveFView.swift
  Puzzling/Puzzling/Presentation/CreateRetrospect/View/TILView.swift
  Puzzling/Puzzling/Presentation/CreateRetrospect/ViewController/BottomSheetViewController.swift
  Puzzling/Puzzling/Presentation/CreateRetrospect/ViewController/CreateRetrospectViewController.swift
  Puzzling/Puzzling/Presentation/CreateRetrospect/ViewController/testViewController.swift
  Puzzling/Puzzling/Util/CustomClass/CustomRadioButton.swift
  Puzzling/Puzzling/Util/Extension/String+.swift
  Puzzling/Puzzling/Util/NameSpace/Image.swift
Labels: 🌱 Feat, 🐰 성우

#21 [Feature] #14 - 개인 대시보드 View 를 부분 구현했습니다.
  Puzzling/Puzzling.xcodeproj/project.pbxproj
  Puzzling/Puzzling/Application/SceneDelegate.swift
  Puzzling/Puzzling/Data/DTO/IndivisualDashboardModel.swift
  Puzzling/Puzzling/Data/DTO/TeamDashboardModel.swift
  Puzzling/Puzzling/Presentation/Home/Common/DashboardMainBoxView.swift
  Puzzling/Puzzling/Presentation/Home/IndivisualDashboard/Component/ActionPlanCollectionViewCell.swift
  Puzzling/Puzzling/Presentation/Home/IndivisualDashboard/Component/HomeMainButton.swift
  Puzzling/Puzzling/Presentation/Home/IndivisualDashboard/View/ActionPlanView.swift
  Puzzling/Puzzling/Presentation/Home/IndivisualDashboard/View/IndivisualCardButtonView.swift
  Puzzling/Puzzling/Presentation/Home/IndivisualDashboard/ViewController/IndivisualDashboardViewController.swift
  Puzzling/Puzzling/Presentation/Home/TeamDashboard/TeamDashboardViewController.swift
  Puzzling/Puzzling/Presentation/Home/TeamDashboard/View/TeamDashboardRankView.swift
  Puzzling/Puzzling/Presentation/Home/TeamDashboard/View/TeamRankPodiumView.swift
  Puzzling/Puzzling/Presentation/Home/TeamDashboard/ViewController/TeamDashboardViewController.swift
  Puzzling/Puzzling/Resource/AssetCatalog/Image.xcassets/Dashboard/Contents.json
  Puzzling/Puzzling/Resource/AssetCatalog/Image.xcassets/Dashboard/puzzleBannerBox.imageset/Contents.json
  Puzzling/Puzzling/Resource/AssetCatalog/Image.xcassets/Dashboard/puzzleBannerBox.imageset/puzzleBannerBox.svg
  Puzzling/Puzzling/Util/Extension/String+.swift
  Puzzling/Puzzling/Util/Extension/UIView+.swift
  Puzzling/Puzzling/Util/NameSpace/Image.swift
Labels: 🌱 Feat, 🦊 규보, ⚙️ Setting

#40 [Fix] #39 - 내 프로젝트 뷰 UI 수정했습니다.
  Puzzling/Puzzling/Application/SceneDelegate.swift
  Puzzling/Puzzling/Data/DTO/MyProjectDataModel.swift
  Puzzling/Puzzling/Presentation/MyProject/View/MyProjectTableHeaderView.swift
  Puzzling/Puzzling/Presentation/MyProject/View/MyProjectTableViewCell.swift
  Puzzling/Puzzling/Presentation/MyProject/ViewController/MyProjectViewController.swift
Labels: 🎈 Fix, 😼 민주

#49 [Feature] #44 - 주간 팀원 회고 상황 조회 API를 연결했습니다.
  Puzzling/Puzzling.xcodeproj/project.pbxproj
  Puzzling/Puzzling.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Puzzling/Puzzling/Application/SceneDelegate.swift
  Puzzling/Puzzling/Data/DTO/Team/ProjectTeamResponse.swift
  Puzzling/Puzzling/Data/DTO/TeamMemberDataModel.swift
  Puzzling/Puzzling/Data/Model/TeamMemberModel.swift
  Puzzling/Puzzling/Network/APIService/ProjectTeamService.swift
  Puzzling/Puzzling/Network/Foundation/APIConst.swift
  Puzzling/Puzzling/Network/Foundation/URLConst.swift
  Puzzling/Puzzling/Presentation/ReviewDetail/ViewController/ReviewDetailViewController.swift
  Puzzling/Puzzling/Presentation/TeamMember/View/TeamMemberTableViewCell.swift
  Puzzling/Puzzling/Presentation/TeamMember/View/TeamMemberView.swift
  Puzzling/Puzzling/Presentation/TeamMember/ViewController/TeamMemberViewController.swift
Labels: 🌱 Feat, 😼 민주

#51 [Feature] #20
  Puzzling/Puzzling/Application/SceneDelegate.swift
Labels: 😼 민주

#52 [Feature] #43 - 회고작성 서버통신을 구현했습니다
  Puzzling/Puzzling.xcodeproj/project.pbxproj
  Puzzling/Puzzling.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Puzzling/Puzzling/Data/DTO/CreateRetrospect/PreviousTemplateResponce.swift
  Puzzling/Puzzling/Data/DTO/CreateRetrospect/ReviewAARRequest.swift
  Puzzling/Puzzling/Data/DTO/CreateRetrospect/ReviewFiveFRequest.swift
  Puzzling/Puzzling/Data/DTO/CreateRetrospect/ReviewTILRequest.swift
  Puzzling/Puzzling/Data/DTO/CreateRetrospect/TemplateCaseResponce.swift
  Puzzling/Puzzling/Data/Model/CreateRetrospectModel/PreviousTemplateModel.swift
  Puzzling/Puzzling/Data/Model/CreateRetrospectModel/ReviewAARModel.swift
  Puzzling/Puzzling/Data/Model/CreateRetrospectModel/ReviewFiveFModel.swift
  Puzzling/Puzzling/Data/Model/CreateRetrospectModel/ReviewTILModel.swift
  Puzzling/Puzzling/Data/Model/CreateRetrospectModel/TemplateCaseModel.swift
  Puzzling/Puzzling/Network/APIService/CreateRetrospect/CreateRetrospectService.swift
  Puzzling/Puzzling/Network/Foundation/URLConst.swift
  Puzzling/Puzzling/Presentation/CreateProject/View/CustomAlertView.swift
  Puzzling/Puzzling/Presentation/CreateRetrospect/View/AARView.swift
  Puzzling/Puzzling/Presentation/CreateRetrospect/ViewController/BottomSheetViewController.swift
  Puzzling/Puzzling/Presentation/CreateRetrospect/ViewController/CreateRetrospectViewController.swift
  Puzzling/Puzzling/Presentation/CreateRetrospect/ViewController/testViewController.swift
Labels: 🌱 Feat, 🐰 성우

#54 [Fix] #53 - 파일 추가되지 않는 오류 수정
  Puzzling/Puzzling.xcodeproj/project.pbxproj
  Puzzling/Puzzling.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Puzzling/Puzzling/Application/SceneDelegate.swift
  Puzzling/Puzzling/Presentation/CreateRetrospect/View/CustomAlert.swift
  Puzzling/Puzzling/Presentation/CreateReview/View/AARView.swift
  Puzzling/Puzzling/Presentation/CreateReview/View/FiveFView.swift
  Puzzling/Puzzling/Presentation/CreateReview/View/TILView.swift
  Puzzling/Puzzling/Presentation/CreateReview/ViewController/BottomSheetViewController.swift
  Puzzling/Puzzling/Presentation/CreateReview/ViewController/CreateRetrospectViewController.swift
  Puzzling/Puzzling/Presentation/CreateReview/ViewController/ReviewTestViewController.swift
Labels: 🎈 Fix, 🐰 성우

#55 [Feature] #41 - 회고상세조회뷰 로직을 구현했습니다.
  Puzzling/Puzzling.xcodeproj/project.pbxproj
  Puzzling/Puzzling/Application/SceneDelegate.swift
  Puzzling/Puzzling/Data/DTO/MyReviewListDataModel.swift
  Puzzling/Puzzling/Data/DTO/ReviewDetailDataModel.swift
  Puzzling/Puzzling/Presentation/MyProject/View/MyProjectTableViewCell.swift
  Puzzling/Puzzling/Presentation/MyProject/ViewController/MyProjectViewController.swift
  Puzzling/Puzzling/Presentation/MyReview/ViewController/MyReviewListViewController.swift
  Puzzling/Puzzling/Presentation/MyReview/ViewController/ProjectListViewController.swift
  Puzzling/Puzzling/Presentation/ReviewDetail/View/ProjectCalendarView.swift
  Puzzling/Puzzling/Presentation/ReviewDetail/View/ReviewDetailCollectionViewCell.swift
  Puzzling/Puzzling/Presentation/ReviewDetail/View/ReviewDetailView.swift
  Puzzling/Puzzling/Presentation/ReviewDetail/ViewController/ReviewDetailViewController.swift
  Puzzling/Puzzling/Presentation/TeamMember/View/TeamMemberCalendarView.swift
  Puzzling/Puzzling/Presentation/TeamMember/ViewController/TeamMemberViewController.swift
  Puzzling/Puzzling/Util/NameSpace/Image.swift
Labels: 🌱 Feat, 😼 민주

#56 [Feature] #48 - Kakao Login을 구현했습니다.
  Puzzling/Puzzling.xcodeproj/project.pbxproj
  Puzzling/Puzzling/Application/AppDelegate.swift
  Puzzling/Puzzling/Application/Info.plist
  Puzzling/Puzzling/Application/KeyChain.swift
  Puzzling/Puzzling/Application/SceneDelegate.swift
  Puzzling/Puzzling/Data/DTO/Auth/PostAuthRequest.swift
  Puzzling/Puzzling/Data/DTO/Auth/TokenResponse.swift
  Puzzling/Puzzling/Data/DTO/Auth/UserResponse.swift
  Puzzling/Puzzling/Data/DTO/TeamMemberDataModel.swift
  Puzzling/Puzzling/Data/Model/Auth/AuthModel.swift
  Puzzling/Puzzling/Data/Model/Auth/TokenModel.swift
  Puzzling/Puzzling/Data/Model/Auth/User.swift
  Puzzling/Puzzling/Data/Model/Auth/UserModel.swift
  Puzzling/Puzzling/Data/Model/TeamMemberModel.swift
  Puzzling/Puzzling/Network/APIService/Auth/AuthService.swift
  Puzzling/Puzzling/Network/Foundation/APIConst.swift
  Puzzling/Puzzling/Presentation/OnBoarding/View/OnBoardingView.swift
  Puzzling/Puzzling/Presentation/OnBoarding/ViewController/EnterProjectViewController.swift
  Puzzling/Puzzling/Presentation/OnBoarding/ViewController/OnBoardingViewController.swift
  Puzzling/Puzzling/Presentation/TeamMember/View/TeamMemberCalendarView.swift
  Puzzling/Puzzling/Presentation/TeamMember/ViewController/TeamMemberViewController.swift
  Puzzling/Puzzling/Resource/AssetCatalog/Image.xcassets/icon/kakaoButton.imageset/Contents.json
  Puzzling/Puzzling/Resource/AssetCatalog/Image.xcassets/icon/kakaoButton.imageset/kakaoButton.png
  Puzzling/Puzzling/Resource/AssetCatalog/Image.xcassets/icon/kakao_login_large_wide.imageset/Contents.json
  Puzzling/Puzzling/Resource/AssetCatalog/Image.xcassets/icon/kakao_login_large_wide.imageset/kakao_login_large_wide.png
  Puzzling/Puzzling/Resource/AssetCatalog/Image.xcassets/icon/puzzle_element2.imageset/Contents.json
  Puzzling/Puzzling/Resource/AssetCatalog/Image.xcassets/icon/puzzle_element2.imageset/puzzle_element.svg
  Puzzling/Puzzling/Util/Extension/UILabel+.swift
  Puzzling/Puzzling/Util/NameSpace/Image.swift
Labels: 🌱 Feat, 😼 민주

#47 [Feature] #33 - 프로젝트 등록 뷰, 초대코드 입력 뷰 API 연결
  Puzzling/Puzzling.xcodeproj/project.pbxproj
  Puzzling/Puzzling.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Puzzling/Puzzling/Data/DTO/DTO.swift
  Puzzling/Puzzling/Data/DTO/Project/CreateProjectResponse.swift
  Puzzling/Puzzling/Data/DTO/Project/PostProfileRequest.swift
  Puzzling/Puzzling/Data/DTO/Project/PostProjectRequest.swift
  Puzzling/Puzzling/Data/DTO/Project/ProjectResponse.swift
  Puzzling/Puzzling/Data/Model/Model.swift
  Puzzling/Puzzling/Data/Model/Project/CreateProjectModel.swift
  Puzzling/Puzzling/Data/Model/Project/InputContentType.swift
  Puzzling/Puzzling/Data/Model/Project/Profile.swift
  Puzzling/Puzzling/Data/Model/Project/Project.swift
  Puzzling/Puzzling/Data/Model/Project/ProjectModel.swift
  Puzzling/Puzzling/Network/APIService/APIService.swift
  Puzzling/Puzzling/Network/APIService/Project/ProjectService.swift
  Puzzling/Puzzling/Network/Foundation/GeneralResponse.swift
  Puzzling/Puzzling/Network/Foundation/URLConst.swift
  Puzzling/Puzzling/Presentation/CreateProject/View/CustomAlertView.swift
  Puzzling/Puzzling/Presentation/CreateProject/View/InputContentView.swift
  Puzzling/Puzzling/Presentation/CreateProject/ViewController/CreateProjectViewController.swift
  Puzzling/Puzzling/Presentation/InvitationCode/ViewController/CreateProfileViewController.swift
  Puzzling/Puzzling/Presentation/InvitationCode/ViewController/InvitationCodeViewController.swift
  Puzzling/Puzzling/Util/NameSpace/Image.swift
Labels: 🌱 Feat, 🐸 정

#58 [Chore] #57 - 카카오 소셜 로그인 에러 해결
  Puzzling/Puzzling.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Puzzling/Puzzling/Network/APIService/Auth/AuthService.swift
  Puzzling/Puzzling/Network/Foundation/APIConst.swift
  Puzzling/Puzzling/Presentation/OnBoarding/ViewController/OnBoardingViewController.swift
Labels: ☂️ Chore, 🐸 정

#65 [Feature] #60 - 토스트메세지를 구현합니다
  Puzzling/Puzzling.xcodeproj/project.pbxproj
  Puzzling/Puzzling/Presentation/CreateReview/ViewController/CreateReViewViewController.swift
  Puzzling/Puzzling/Presentation/CreateReview/ViewController/ReviewTestViewController.swift
  Puzzling/Puzzling/Resource/AssetCatalog/Image.xcassets/icon/check-fill.imageset/Contents.json
  Puzzling/Puzzling/Resource/AssetCatalog/Image.xcassets/icon/check-fill.imageset/iconamoon_check-fill.png
  Puzzling/Puzzling/Util/Extension/UIViewController+.swift
  Puzzling/Puzzling/Util/NameSpace/Image.swift
Labels: 🌱 Feat, 🐰 성우

#63 [Chore] #59 - 자잘한 오류 수정
  Puzzling/Puzzling.xcodeproj/project.pbxproj
  Puzzling/Puzzling.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Puzzling/Puzzling/Application/Info.plist
  Puzzling/Puzzling/Application/SceneDelegate.swift
  Puzzling/Puzzling/Data/Model/Auth/User.swift
  Puzzling/Puzzling/Data/Model/Auth/UserModel.swift
  Puzzling/Puzzling/Network/APIService/ProjectServiceTemporary.swift
  Puzzling/Puzzling/Network/Foundation/APIConst.swift
  Puzzling/Puzzling/Network/Foundation/URLConst.swift
  Puzzling/Puzzling/Presentation/CreateProject/View/CustomAlertView.swift
  Puzzling/Puzzling/Presentation/CreateProject/ViewController/CreateProjectViewController.swift
  Puzzling/Puzzling/Presentation/Home/Main/ViewController/HomeViewController.swift
  Puzzling/Puzzling/Presentation/InvitationCode/ViewController/CreateProfileViewController.swift
  Puzzling/Puzzling/Presentation/InvitationCode/ViewController/InvitationCodeViewController.swift
  Puzzling/Puzzling/Presentation/MyPage/ViewController/MyPageViewController.swift
  Puzzling/Puzzling/Presentation/OnBoarding/View/EnterProjectView.swift
  Puzzling/Puzzling/Presentation/OnBoarding/ViewController/EnterProjectViewController.swift
  Puzzling/Puzzling/Presentation/OnBoarding/ViewController/OnBoardingViewController.swift
  Puzzling/Puzzling/Presentation/TabBar/TabBarController.swift
  Puzzling/Puzzling/Util/Extension/Config+.swift
Labels: ☂️ Chore, 🐸 정

#67 [Feature] 홈뷰와 이어진 뷰들을 잇습니다.
  Puzzling/Puzzling.xcodeproj/project.pbxproj
  Puzzling/Puzzling.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Puzzling/Puzzling/Application/SceneDelegate.swift
  Puzzling/Puzzling/Presentation/Home/Common/Component/MainPuzzleCollectionViewCell.swift
  Puzzling/Puzzling/Presentation/Home/Common/View/DashboardMainBoxView.swift
  Puzzling/Puzzling/Presentation/Home/Common/View/MainPuzzleCollectionView.swift
  Puzzling/Puzzling/Presentation/Home/IndivisualDashboard/ViewController/IndivisualDashboardViewController.swift
  Puzzling/Puzzling/Presentation/Home/Main/ViewController/HomeBottomSheetViewController.swift
  Puzzling/Puzzling/Presentation/Home/Main/ViewController/HomeViewController.swift
  Puzzling/Puzzling/Presentation/TeamMember/ViewController/TeamMemberViewController.swift
  Puzzling/Puzzling/Resource/AssetCatalog/Assets.xcassets/AppIcon.appiconset/Contents.json
  Puzzling/Puzzling/Resource/AssetCatalog/Assets.xcassets/AppIcon.appiconset/KakaoTalk_Image_2023-07-21-08-28-25.png
Labels: 🌱 Feat, 🎈 Fix, 🎀 Add, ☁️ Refactor, ☂️ Chore, 🍑 Merge, 🦊 규보

#70 [Feature] #69 - 뷰를 연결했습니다
  Puzzling/Puzzling.xcodeproj/project.pbxproj
  Puzzling/Puzzling/Presentation/CreateReview/ViewController/BottomSheetViewController.swift
  Puzzling/Puzzling/Presentation/CreateReview/ViewController/CreateReViewViewController.swift
  Puzzling/Puzzling/Presentation/CreateReview/ViewController/ReviewTestViewController.swift
  Puzzling/Puzzling/Presentation/Home/IndivisualDashboard/ViewController/IndivisualDashboardViewController.swift
  Puzzling/Puzzling/Presentation/Home/Main/ViewController/HomeViewController.swift
  Puzzling/Puzzling/Util/NameSpace/Image.swift
Labels: 🌱 Feat, ☂️ Chore, 🐰 성우

#71 [Feature] #62 - 마이페이지 뷰 간의 데이터 넘기기를 구현했습니다.
  Puzzling/Puzzling.xcodeproj/project.pbxproj
  Puzzling/Puzzling/Application/SceneDelegate.swift
  Puzzling/Puzzling/Presentation/MyProject/ViewController/MyProjectViewController.swift
  Puzzling/Puzzling/Presentation/MyReview/View/MyReviewListCollectionViewCell.swift
  Puzzling/Puzzling/Presentation/MyReview/ViewController/MyPageBottomSheetViewController.swift
  Puzzling/Puzzling/Presentation/MyReview/ViewController/MyReviewListViewController.swift
  Puzzling/Puzzling/Presentation/OnBoarding/ViewController/OnBoardingViewController.swift
  Puzzling/Puzzling/Presentation/ReviewDetail/View/ProjectCalendarView.swift
  Puzzling/Puzzling/Presentation/ReviewDetail/View/ReviewDetailEmptyView.swift
  Puzzling/Puzzling/Presentation/ReviewDetail/View/ReviewDetailView.swift
  Puzzling/Puzzling/Presentation/ReviewDetail/ViewController/ReviewDetailViewController.swift
  Puzzling/Puzzling/Presentation/TeamMember/View/TeamMemberCalendarView.swift
  Puzzling/Puzzling/Presentation/TeamMember/ViewController/TeamMemberViewController.swift
Labels: 🌱 Feat, 🎈 Fix, 😼 민주

#76 [Feature] #73 - 전체 코드들을 연결합니다
  Puzzling/Puzzling/Application/SceneDelegate.swift
  Puzzling/Puzzling/Presentation/CreateReview/ViewController/CreateReViewViewController.swift
  Puzzling/Puzzling/Presentation/Home/Main/ViewController/HomeViewController.swift
  Puzzling/Puzzling/Presentation/MyProject/View/MyProjectTableViewCell.swift
  Puzzling/Puzzling/Presentation/MyProject/ViewController/MyProjectViewController.swift
  Puzzling/Puzzling/Presentation/MyReview/ViewController/MyPageBottomSheetViewController.swift
  Puzzling/Puzzling/Presentation/MyReview/ViewController/MyReviewListViewController.swift
  Puzzling/Puzzling/Presentation/ReviewDetail/View/ProjectCalendarView.swift
  Puzzling/Puzzling/Presentation/ReviewDetail/ViewController/ReviewDetailViewController.swift
  Puzzling/Puzzling/Presentation/TeamMember/ViewController/TeamMemberViewController.swift
  Puzzling/Puzzling/Util/Extension/Date+.swift
Labels: 🌱 Feat, ☂️ Chore, 🐰 성우

#77 [Refactor] #72 - 버튼 추가
  Puzzling/Puzzling.xcodeproj/project.pbxproj
  Puzzling/Puzzling/Presentation/MyProject/View/MyProjectTableViewCell.swift
  Puzzling/Puzzling/Presentation/MyProject/ViewController/MyProjectViewController.swift
Labels: 🎈 Fix, 😼 민주

#78 [Refactor] #68 - 코드 리팩토링
  Puzzling/Puzzling.xcodeproj/project.pbxproj
  Puzzling/Puzzling/Data/DTO/MyProjectDataModel.swift
  Puzzling/Puzzling/Data/DTO/MyReviewListDataModel.swift
  Puzzling/Puzzling/Data/DTO/ReviewDetailDataModel.swift
  Puzzling/Puzzling/Data/Model/MyProject/TeamMemberModel.swift
  Puzzling/Puzzling/Data/Model/Project/ProjectCycleModel.swift
  Puzzling/Puzzling/Data/Model/Project/TextFieldNotificationModel.swift
  Puzzling/Puzzling/Network/APIService/DashBoard/ProjectServiceTemporary.swift
  Puzzling/Puzzling/Network/APIService/ProjectTeam/ProjectTeamService.swift
  Puzzling/Puzzling/Presentation/CreateReview/View/FiveFView.swift
  Puzzling/Puzzling/Presentation/CreateReview/View/TILView.swift
  Puzzling/Puzzling/Presentation/CreateReview/ViewController/BottomSheetViewController.swift
  Puzzling/Puzzling/Presentation/CreateReview/ViewController/CreateReViewViewController.swift
  Puzzling/Puzzling/Presentation/Home/Common/Component/MainPuzzleCollectionViewCell.swift
  Puzzling/Puzzling/Presentation/Home/Common/Component/PuzzleBoardCollectionViewCell.swift
  Puzzling/Puzzling/Presentation/Home/Common/View/DashboardMainBoxView.swift
  Puzzling/Puzzling/Presentation/Home/Common/View/MainPuzzleCollectionView.swift
  Puzzling/Puzzling/Presentation/Home/Common/ViewController/PuzzleBoardViewController.swift
  Puzzling/Puzzling/Presentation/Home/IndivisualDashboard/Component/ActionPlanCollectionViewCell.swift
  Puzzling/Puzzling/Presentation/Home/IndivisualDashboard/Component/HomeMainButton.swift
  Puzzling/Puzzling/Presentation/Home/IndivisualDashboard/View/ActionPlanView.swift
  Puzzling/Puzzling/Presentation/Home/IndivisualDashboard/View/IndivisualCardButtonView.swift
  Puzzling/Puzzling/Presentation/Home/IndivisualDashboard/ViewController/IndivisualDashboardViewController.swift
  Puzzling/Puzzling/Presentation/Home/Main/Component/HomeBottomSheetCellButton.swift
  Puzzling/Puzzling/Presentation/Home/Main/Component/HomeBottomSheetTableViewCell.swift
  Puzzling/Puzzling/Presentation/Home/Main/View/HomeSegmentedView.swift
  Puzzling/Puzzling/Presentation/Home/Main/View/HomeTitleBarView.swift
  Puzzling/Puzzling/Presentation/Home/Main/View/PopUpDayView.swift
  Puzzling/Puzzling/Presentation/Home/Main/ViewController/HomeBottomSheetViewController.swift
  Puzzling/Puzzling/Presentation/Home/Main/ViewController/HomeViewController.swift
  Puzzling/Puzzling/Presentation/Home/TeamDashboard/Component/TeamRankPodiumCell.swift
  Puzzling/Puzzling/Presentation/Home/TeamDashboard/Component/TeamRankTableViewCell.swift
  Puzzling/Puzzling/Presentation/Home/TeamDashboard/View/TeamDashboardRankView.swift
  Puzzling/Puzzling/Presentation/Home/TeamDashboard/View/TeamRankPodiumView.swift
  Puzzling/Puzzling/Presentation/Home/TeamDashboard/ViewController/TeamDashboardViewController.swift
  Puzzling/Puzzling/Presentation/MyProject/View/MyProjectTableHeaderView.swift
  Puzzling/Puzzling/Presentation/MyProject/View/MyProjectTableViewCell.swift
  Puzzling/Puzzling/Presentation/MyProject/ViewController/MyProjectViewController.swift
  Puzzling/Puzzling/Presentation/MyReview/View/MyReviewListCollectionViewCell.swift
  Puzzling/Puzzling/Presentation/MyReview/View/ProjectNameCollectionReusableView.swift
  Puzzling/Puzzling/Presentation/MyReview/View/ProjectNameTableViewCell.swift
  Puzzling/Puzzling/Presentation/MyReview/ViewController/MyPageBottomSheetViewController.swift
  Puzzling/Puzzling/Presentation/MyReview/ViewController/MyReviewListViewController.swift
  Puzzling/Puzzling/Presentation/OnBoarding/View/EnterProjectView.swift
  Puzzling/Puzzling/Presentation/OnBoarding/View/OnBoardingView.swift
  Puzzling/Puzzling/Presentation/OnBoarding/ViewController/EnterProjectViewController.swift
  Puzzling/Puzzling/Presentation/ReviewDetail/View/ProjectCalendarView.swift
  Puzzling/Puzzling/Presentation/ReviewDetail/View/ReviewDetailCollectionViewCell.swift
  Puzzling/Puzzling/Presentation/ReviewDetail/View/ReviewDetailEmptyView.swift
  Puzzling/Puzzling/Presentation/ReviewDetail/View/ReviewDetailView.swift
  Puzzling/Puzzling/Presentation/ReviewDetail/ViewController/ReviewDetailViewController.swift
  Puzzling/Puzzling/Presentation/TabBar/TabBarController.swift
  Puzzling/Puzzling/Presentation/TeamMember/View/TeamMemberCalendarView.swift
  Puzzling/Puzzling/Presentation/TeamMember/View/TeamMemberCustomHeaderView.swift
  Puzzling/Puzzling/Presentation/TeamMember/View/TeamMemberTableViewCell.swift
  Puzzling/Puzzling/Presentation/TeamMember/ViewController/TeamMemberViewController.swift
  Puzzling/Puzzling/Util/NameSpace/Image.swift
Labels: ☁️ Refactor, 🐸 정

#80 [Fix] #79 - 네비게이션 바 삭제 완료
  Puzzling/Puzzling/Application/SceneDelegate.swift
  Puzzling/Puzzling/Presentation/Home/Main/ViewController/HomeViewController.swift
  Puzzling/Puzzling/Presentation/MyProject/ViewController/MyProjectViewController.swift
  Puzzling/Puzzling/Presentation/ReviewDetail/ViewController/ReviewDetailViewController.swift
  Puzzling/Puzzling/Presentation/TabBar/TabBarController.swift
Labels: 🎈 Fix, 😼 민주

#84 [Fix] #83 - RootVC를 수정합니다
  Puzzling/Puzzling/Presentation/ReviewDetail/ViewController/ReviewDetailViewController.swift
Labels: 🎈 Fix, 🐰 성우

#85 [Fix] #81 - 온보딩 뷰 토큰 만료 문제 해결
  Puzzling/Puzzling.xcodeproj/project.pbxproj
  Puzzling/Puzzling/Presentation/Home/Main/ViewController/HomeViewController.swift
  Puzzling/Puzzling/Presentation/OnBoarding/ViewController/OnBoardingViewController.swift
Labels: 🎈 Fix, 😼 민주

#88 [Fix] #87 - 레이아웃 문제 해결
  Puzzling/Puzzling/Presentation/TeamMember/ViewController/TeamMemberViewController.swift
Labels: 🎈 Fix, 😼 민주

#91 [Fix] #89 - BottomSheet 터치영역을 조정합니다
  Puzzling/Puzzling/Presentation/CreateReview/ViewController/BottomSheetViewController.swift
  Puzzling/Puzzling/Presentation/CreateReview/ViewController/CreateReViewViewController.swift
Labels: 🎈 Fix, 🐰 성우

#92 [Fix] #90 - 메이져한 UI Bug 를 고칩니다.
  Puzzling/Puzzling.xcodeproj/project.pbxproj
  Puzzling/Puzzling/Application/SceneDelegate.swift
  Puzzling/Puzzling/Presentation/Home/Common/Component/MainPuzzleCollectionViewCell.swift
  Puzzling/Puzzling/Presentation/Home/Common/View/MainPuzzleCollectionView.swift
  Puzzling/Puzzling/Presentation/Home/Main/ViewController/HomeViewController.swift
  Puzzling/Puzzling/Presentation/ReviewDetail/ViewController/ReviewDetailViewController.swift
Labels: 🎈 Fix, 🦊 규보

#94 [Fix] #90 - 마이너한 UI Bug 를 고쳤습니다.
  Puzzling/Puzzling/Application/Info.plist
  Puzzling/Puzzling/Presentation/CreateReview/ViewController/CreateReViewViewController.swift
  Puzzling/Puzzling/Presentation/ReviewDetail/ViewController/ReviewDetailViewController.swift
Labels: 🎈 Fix, 🦊 규보

#95 [Fix] #90 - 마이너한 버그 수정 및 데이터 로딩 인디케이터를 추가했습니다.
  Puzzling/Puzzling/Presentation/ReviewDetail/View/ProjectCalendarView.swift
  Puzzling/Puzzling/Presentation/TeamMember/ViewController/TeamMemberViewController.swift
Labels: 🌱 Feat, 🎈 Fix, 🦊 규보

#97 [Fix] #96 - 캘린더 요일 수정
  Puzzling/Puzzling/Presentation/TeamMember/View/TeamMemberCalendarView.swift
Labels: 🎈 Fix, 😼 민주

#99 [Fix] #98 - 프로젝트 참여 시 프로젝트 아이디 전달
  Puzzling/Puzzling/Presentation/InvitationCode/ViewController/CreateProfileViewController.swift
Labels: 🎈 Fix, 🐸 정
